### ISSUE TITLE
compilation database not generated for OpenWRT

### ISSUE THREAD

**Issue by maindoor** [nickdiego/compiledb#69]
Hi, 
I tried to build a using a cross compilation toolchain using make and used compiledb to generate
compilation database, but it kind of hung after the compilation was done for about 10mins. So I Ctrl-C'd
it and got out. I didn't find any json files in my build dir. What do you think could have wrong ? Here is the last output:
make[1]: Leaving directory '/home/sk/openwrt_trunk/attitude-adjustment-38900'
()
## Processing build commands from <fdopen>

^Cmake[14748]: *** wait: No child processes.  Stop.
make[14748]: *** Waiting for unfinished jobs....
make[14748]: *** wait: No child processes.  Stop.
make[14747]: *** wait: No child processes.  Stop.
make[14747]: *** Waiting for unfinished jobs....
make[14747]: *** wait: No child processes.  Stop.
make[14746]: *** wait: No child processes.  Stop.
make[14746]: *** Waiting for unfinished jobs....
make[14746]: *** wait: No child processes.  Stop.
make[14745]: *** wait: No child processes.  Stop.
make[14745]: *** Waiting for unfinished jobs....
make[14745]: *** wait: No child processes.  Stop.
make[14744]: *** wait: No child processes.  Stop.
make[14744]: *** Waiting for unfinished jobs....
make[14744]: *** wait: No child processes.  Stop.
make[14743]: *** wait: No child processes.  Stop.
make[14743]: *** Waiting for unfinished jobs....
make[14743]: *** wait: No child processes.  Stop.
make[14742]: *** [/home/sk/openwrt_trunk871/attitude-adjustment-38900/include/verbose.mk] Interrupt
make[14741]: *** [/home/sk/openwrt_trunk871/attitude-adjustment-38900/include/verbose.mk] Interrupt
make[14740]: *** [/home/sk/openwrt_trunk871/attitude-adjustment-38900/include/verbose.mk] Interrupt
make[14739]: *** [/home/sk/openwrt_trunk871/attitude-adjustment-38900/include/verbose.mk] Interr

**Comment by nickdiego** [comment]
Thanks for reporting this.

What's the exact command are you running?

Essentially to be able to parse the build commands `compiledb` needs the build log. From the logs you've postedm, it seems like openwrt uses recursive makefiles (didn't build it before, so not sure), if that's the case I would recommend you to try to do the process in 2 steps:

1. Get/store the build log in some file, for example, to build CUPS package [1]:
```sh
make V=s package/cups/compile | tee build.log
```
_PS: Check if the `build.log` file contains build commands (e.g: `gcc -c .... -o ...`)_

2. Generate json compilation database using the build log as input:
```sh
compiledb --parse build.log
```

[1] https://oldwiki.archive.openwrt.org/doc/howto/build#building_single_packages

**Comment by maindoor** [comment]
I'm sorry, I had moved on to another project. I will get back to this within the next month or so. We'll get this sorted. Thank you for such a great tool and support.

**Comment by Alchiadus** [comment]
Unfortunately the suggestion did not work for me. I built OpenWRT successfully and tried to generate the compile commands from the `build.log` (as can be expected this is a large file, about 16MB) as follows:
```bash
$ make -j $(nproc) V=s | tee build.log
...
$ compiledb --parse build.log
Traceback (most recent call last):
  File "/home/ixon/.local/bin/compiledb", line 10, in <module>
    sys.exit(cli())
  File "/home/ixon/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ixon/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ixon/.local/lib/python2.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/ixon/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ixon/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ixon/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ixon/.local/lib/python2.7/site-packages/compiledb/cli.py", line 92, in cli
    use_full_path, command_style)
  File "/home/ixon/.local/lib/python2.7/site-packages/compiledb/__init__.py", line 106, in generate
    command_style=command_style)
  File "/home/ixon/.local/lib/python2.7/site-packages/compiledb/__init__.py", line 54, in generate_json_compdb
    use_full_path=use_full_path, command_style=command_style)
  File "/home/ixon/.local/lib/python2.7/site-packages/compiledb/parser.py", line 103, in parse_build_log
    working_dir = dir_stack[-1]
IndexError: list index out of range
```

**Comment by nickdiego** [comment]
It seems to be a problem with enter/leave directory parsing.

> `$ make -j $(nproc) V=s | tee build.log`

You should add `-w` as I recommended above. (atm we don't an option to ignore enter/leave dir messages).

Anyway, could you upload your build log file somewhere so that we can debug the issue?

Thanks.

**Comment by Alchiadus** [comment]
Unfortunately I did not keep the build log and my attempts to reproduce the crash have not been successful.

**Comment by Jacob-Vanthof** [comment]
So, I wanted to give some closure to this issue as I ran into this with a build system that is based on an older version of openwrt. The problem is that in the openwrt output likes to sometimes add ANSI Escape codes in front of the make Enter and Leaving directory lines. This would cause the dir_stack to be popped twice when it put one before an enter and pop the "dir_list" to be an empty list (since it saw two "leaving directory" lines in a row).

Here is an example of a line that would fail the python regex parsing.
![Image](https://github.com/user-attachments/assets/e846c491-32ab-49a4-ae51-028c0d45cf34)
