### ISSUE TITLE
compiledb for clang and/or MinGW GCC generates empty compile_commands.json

### ISSUE THREAD

**Issue by wireless-road** [nickdiego/compiledb#96]
Hi!
Have pretty simple C project containing just one source file `hello.c`:

```
#include <stdio.h>

int main()
{
	printf("Hello world!\n");	 
	return 0;
}
```
here is `Makefile `for this project:
```
clang:
	@echo 'clangg'
	clang.exe -IC:\tools\MinGW\i686-w64-mingw32\include hello.c -v -o hello.exe

mingw:
	C:\tools\MinGW\bin\gcc.exe -IC:\tools\MinGW\i686-w64-mingw32\include hello.c -v -o hello.exe
```
I've compiledb installed by:
`pip install compiledb`

So, when I'm trying to run `compiledb make clang`:
It shows me following output:
```
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: c:\Program Files\LLVM\bin
 "c:\\Program Files\\LLVM\\bin\\clang.exe" -cc1 -triple x86_64-pc-windows-msvc19.24.28315 -emit-obj -mrelax-all -mincremental-linker-compatible -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.c -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -dwarf-column-info -momit-leaf-frame-pointer -v -resource-dir "c:\\Program Files\\LLVM\\lib\\clang\\9.0.0" -I "C:\\tools\\MinGW\\i686-w64-mingw32\\include" -internal-isystem "c:\\Program Files\\LLVM\\lib\\clang\\9.0.0\\include" -internal-isystem "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18362.0\\ucrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\winrt" -fdebug-compilation-dir "C:\\cms_new\\cms_iot_sw_package\\sources\\iot\\hello\\src" -ferror-limit 19 -fmessage-length 210 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.24.28315 -fdelayed-template-parsing -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -faddrsig -o "C:\\Users\\ALMAZ~1.KHA\\AppData\\Local\\Temp\\hello-c576e2.o" -x c hello.c
clang -cc1 version 9.0.0 based upon LLVM 9.0.0 default target x86_64-pc-windows-msvc
#include "..." search starts here:
#include <...> search starts here:
 C:\tools\MinGW\i686-w64-mingw32\include
 c:\Program Files\LLVM\lib\clang\9.0.0\include
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include
 C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt
 C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared
 C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um
 C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt
End of search list.
 "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\Hostx64\\x64\\link.exe" -out:hello.exe -defaultlib:libcmt "-libpath:C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\lib\\x64" "-libpath:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.18362.0\\ucrt\\x64" "-libpath:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.18362.0\\um\\x64" -nologo "C:\\Users\\ALMAZ~1.KHA\\AppData\\Local\\Temp\\hello-c576e2.o"
```
But generated `compile_commands.json` contains just square brackets:
`[]`

Same if I try to compile by `compiledb make mingw`.

So is compiledb can work at Windows OS?

**Comment by TheGreatRambler** [comment]
I have the same error, but in my case, the file is completely empty.

**Comment by wireless-road** [comment]
Unfortunately, `-n` didn't help.
I run compiledb from source with enabled debug info and it shows me following:
```
## Processing build commands from <fdopen>
Line 1: Failed to parse build command [Details: (<class 'bashlex.tokenizer.MatchedPairError'>) unexpected EOF while looking for matching '`' (position 78)]. Ignoring: 'make: Entering directory `/c/sw_package/sources/iot/hello/src''
New command: C:\tools\MinGW\bin\gcc.exe -IC:\tools\MinGW\i686-w64-mingw32\include hello.c -v --debug -o hello.exe
Line 3: Failed to parse build command [Details: (<class 'bashlex.tokenizer.MatchedPairError'>) unexpected EOF while looking for matching '`' (position 77)]. Ignoring: 'make: Leaving directory `/c/sw_package/sources/iot/hello/src''
## Loaded compilation database with 0 entries from compile_commands.json
## Writing compilation database with 0 entries to compile_commands.json
## Done.
```
Seems that ` symbols breaks everything but when I run `compiledb make mingw` from command line I didn't see any `Entering directory` and  `Leaving directory` messages at all.
Can't understand how to fix that.

**Comment by TheGreatRambler** [comment]
Can;t clang generate compile_commands.json files natively?

**Comment by parhusip** [comment]
I have the same issue, my compile_commands.json just show:
[]

**Comment by sonulohani** [comment]
Same with me. I am getting compile_commands.json with only [] in Windows

**Comment by J-keaper** [comment]
I encountered the same error. I fix this through using `make | compiledb` instead of `compiledb make`. See this [Issue](https://github.com/nickdiego/compiledb/issues/102)

**Comment by imran27** [comment]
Same issue with me too.

I am working on a huge project that generally uses a couple of different compilers to compile for different embedded platforms, all on a remote ubuntu machine.

All I wanted to do is have a compilation db to get proper autocompletion, code jumping/navigation etc.

I exported the make -Bnwk output to a build.log, copied it to my local machine and used compiledb.exe --parse build.log and it didn't work. Also tried cat build.log | compiledb.exe for each of the following cases.

I tried removing all binary characters, removing the entire path of compilers and replacing them with just gcc/clang/CC & g++/clang++/CXX, no avail.

I keep getting just [] in my compiled_commands.json

I hope there is some workaround.

**Comment by andrewstevens-infineon** [comment]
I ran into this Issue working under msys on a Windows host.   As a python package compiledb relies on the standard python pathname processing built-ins.   These, of course, do not handle the special pathname conventions Posix shell environments like MSYS or Cygwin use to represent Windows drive-letters.

As a result joining the current working dir and the filename path captured from make does not produce a correct legal windows pathname.   This causes the check that the file corresponding to the joined pathname exists to fail(unless you've specifiied -S) no entry is generated.     Even if you specify -S the pathnames are mostly mangled/useless.

I've created a PR (#110) with a small patch that fixes this.     Feedback from folks using cygwin etc welcome!

**Comment by AJigsawnHalo** [comment]
Same issue here. compiledb only produces a `compile_commands.json` that only contains `[ ]`  when run in a `build` folder. Interestingly when I ran it at the project's root folder it produces a `compile_commands.json` file that contains an entry for the main.cpp file in there but not for .cpp files inside other folders.

Also I tried running compiledb on the same project inside WSL2 and it works perfectly.

**Comment by AqilCont** [comment]
I also have this issue. Is there any way compiledb can support MSVC? I would love to see some sort of output after trying at least 5 diffirent ways to try to generate this illusive file.

**Comment by ericLemanissier** [comment]
I noticed that compiledb puts in compilation database only the files which are at the root of the project, but not the files which are in subdirectories. I guess this could be because it does not handle properly windows' path separator `\` ?

**Comment by Rixium** [comment]
I had the same issue.
Removing the .exe after my compiler path worked for me.

You'll have to add it back in manually to the generated compile_commands.json after though.

**Comment by aljohnston112** [comment]
I have this issue building a package with a custom Makefile for EDK2.

**Comment by aljohnston112** [comment]
I found a great solution of StackOverflow
```
make clean;make VERBOSE=y all &> make_output.txt
compiledb --parse make_output.txt
```
https://stackoverflow.com/questions/21134120/how-to-turn-makefile-into-json-compilation-database

**Comment by mlt** [comment]
Parsing verbose output did not do it for me if libtool is used. I remember it used to work before I added libtool in the mix.
```sh
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..     -fno-omit-frame-pointer -Werror=pointer-arith -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o ../main.c &&\
mv -f $depbase.Tpo $depbase.Po
```
CommandProcessor.process -> run_cmd -> subprocess.check_output fails to run `echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'` with an error `| was unexpected at this time.`.
```python
>>> subprocess.check_output("""echo main.o | sed 's|[^/]*$|.deps/&|;s|\\.o$||'""", shell=True)
| was unexpected at this time.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/ucrt64/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/ucrt64/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'' returned non-zero exit status 1.
```
However, if I replace single quotes with double:
```
>>> subprocess.check_output("""echo main.o | sed "s|[^/]*$|.deps/&|;s|\\.o$||" """, shell=True)
b'.deps/main.o \n'
```

**Comment by mlt** [comment]
Well, this is ugly, but it works for me under msys2/ucrt64 & MSVC for autotools with libtool
<details>
  <summary>Patch</summary>

```diff
diff --git a/compiledb/parser.py b/compiledb/parser.py
index 9f4c550..d364da6 100755
--- a/compiledb/parser.py
+++ b/compiledb/parser.py
@@ -18,6 +18,7 @@
 #   You should have received a copy of the GNU General Public License
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
+import sys
 import bashlex
 import re
 import logging
@@ -29,7 +30,7 @@ from compiledb.utils import run_cmd
 cc_compile_regex = re.compile(r"^.*-?g?cc-?[0-9.]*$|^.*-?clang-?[0-9.]*$")
 cpp_compile_regex = re.compile(r"^.*-?[gc]\+\+-?[0-9.]*$|^.*-?clang\+\+-?[0-9.]*$")
 file_regex = re.compile(r"^.+\.c$|^.+\.cc$|^.+\.cpp$|^.+\.cxx$|^.+\.s$", re.IGNORECASE)
-compiler_wrappers = {"ccache", "icecc", "sccache"}
+compiler_wrappers = {"ccache", "icecc", "sccache", '/bin/sh', './libtool', '--tag=CC', '--mode=compile'}
 
 # Leverage `make --print-directory` option
 make_enter_dir = re.compile(r"^\s*make\[\d+\]: Entering directory [`\'\"](?P<dir>.*)[`\'\"]\s*$")
@@ -152,6 +153,9 @@ def parse_build_log(build_log, proj_dir, exclude_files, command_style=False, add
 
             logger.debug("Adding command {}: {}".format(len(result.compdb), command_str))
 
+            if sys.platform == 'win32':
+                working_dir = re.sub(r'^(?:/mnt|/cygdrive)?/([a-zA-Z])/', r'\1:/', working_dir)
+
             if command_style:
                 result.compdb.append({
                     'directory': working_dir,
@@ -196,7 +200,7 @@ class CommandProcessor(bashlex.ast.nodevisitor):
             for s in substs:
                 start, end = s.command.pos
                 s_cmd = line[start:end]
-                out = run_cmd(s_cmd, shell=True, cwd=wd)
+                out = run_cmd(s_cmd.replace("'", '"'), shell=True, cwd=wd)
                 start, end = s.pos
                 preprocessed[start:end] = out.strip()
             preprocessed = ''.join(preprocessed)
```

</details>
